name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - run: |
          npm ci
      - name: Build
        run: |
          npm run build --if-present
      - name: Set Git user identity
        run: |
          git config --global user.email "mayurgurav0297@gmail.com"
          git config --global user.name "Coder-Within-Me"
      - name: Publish
        run: npx angular-cli-ghpages --dir=docs/browser --no-silent
